# Generated by Django 5.1.2 on 2024-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_comment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(),
        ),
    ]
